name: 'Terraform_Deploy_Github_Priyanka'

on:
  push:
    branches: [ "main" ]
  pull_request: 

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
     # ARM_CLIENT_ID: "${{ secrets.AZURE_AD_CLIENT_ID }}"
      ARM_CLIENT_ID: 09537e4f-3282-40cd-95c5-8203b9e3b61a
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_AD_CLIENT_SECRET }}"
      storage_account_name: "${{ secrets.STORAGE_ACCOUNT_NAME }}"
      container_name: "${{ secrets.CONTAINER_NAME }}"
      key: "${{ secrets.KEY }}"
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    - name: List Files in Terraform Directory
      run: |
        ls -R ./terraform

    - name: Print Current Working Directory
      run: |
        pwd
    - name: Debug Secrets
      run: |
        echo "Storage Account Name: ${{ secrets.STORAGE_ACCOUNT_NAME }}"
        echo "Container Name: ${{ secrets.CONTAINER_NAME }}"
        echo "Key: ${{ secrets.KEY }}"
    #- name: Setup Terraform
    #  uses: hashicorp//terraform-github-actions@master
    #  with:
    #    terraform_wrapper: false
    #    cli_config_credentials_token: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Format
      run: |
        terraform fmt -check ./terraform

    - name: Terraform Init
      uses: hashicorp//terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_working_dir: "./terraform/Infrastructure_Creation"
        tf_actions_subcommand: 'init'

    - name: Terraform Plan
      uses: hashicorp//terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_working_dir: "./terraform/Infrastructure_Creation"
        tf_actions_subcommand: 'plan'

    - name: Terraform Apply
      uses: hashicorp//terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_working_dir: "./terraform/Infrastructure_Creation"
        tf_actions_subcommand: 'apply'
     # run: terraform apply -auto-approve
